# Alacritty Configuration - High Readability & Highlighting
# Alacritty >= 0.12 uses TOML format

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
opacity = 0.95
padding = { x = 10, y = 10 }
dynamic_padding = true

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
size = 11.5
offset = { x = 0, y = 0 }

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5c2e7"

[colors.normal]
black   = "#45475a"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#bac2de"

[colors.bright]
black   = "#585b70"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#a6adc8"

[colors.selection]
text = "CellForeground"
background = "#313244"

[cursor]
style = "Beam" # or "Block", "Underline"
vi_mode_style = "Block"
blink_interval = 500
unfocused_hollow = true
thickness = 0.2

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
]

[shell]
program = "/bin/bash"
args = ["--login"]

